Repository NOWSOPT-CDSP-WEB-1/Brunch-Web-Client, pull requests merged in 2024-05, with the labels that each got.

#10 [Init/#9] path alias 추가
  package.json
  src/main.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🔥 Init

#15 [Feat/#11] 메인페이지 배너 추가
  package.json
  public/banner-close.svg
  public/banner.svg
  public/brunch_logo_b.png
  public/icn_search.png
  public/long Black bar.svg
  src/Router.tsx
  src/layout/Homestyle.ts
  src/pages/home/Home.tsx
  src/styles/reset.ts
  tsconfig.json
  yarn.lock
Labels: 🧸 Feature

#19 [Init/#16] Icon 세팅 추가
  index.html
  src/components/Icon/Icon.tsx
  src/components/index.ts
  src/pages/home/Home.tsx
  src/styles/icons.ts
  src/styles/theme.ts
Labels: 🔥 Init

#24 [Feat/#22] 아티클 카드 컴포넌트 및 카드 리스트 뷰 추가
  .eslintrc.json
  index.html
  public/assets/images/book.jpeg
  src/Router.tsx
  src/components/ArticleCard/index.tsx
  src/components/Icon/index.tsx
  src/components/index.ts
  src/pages/book/Book.tsx
  src/pages/book/_component/ArticleList.tsx
  src/styles/icons.ts
  src/styles/reset.ts
  src/styles/theme.ts
  src/utils/convertTwoDigit.ts
  tsconfig.json
Labels: 🧸 Feature

#32 [Feat/#23] 메인페이지 캐러셀 추가 및 메인페이지 충돌 해결
  package.json
  public/brunch-logo.svg
  public/icon/arrow-left.svg
  public/icon/arrow-right.svg
  public/icon/heart.svg
  src/components/Logo/index.tsx
  src/components/index.ts
  src/components/libraryHeader1.tsx
  src/layout/Homestyle.ts
  src/pages/book/_component/ArticleList.tsx
  src/pages/home/Home.tsx
  src/pages/home/_components/KeywordTable/index.tsx
  src/pages/home/_components/MainCarousel/config.tsx
  src/pages/home/_components/MainCarousel/index.tsx
  src/pages/home/_components/MainCarousel/types.ts
  src/pages/home/_components/MainIntro/index.tsx
  src/pages/library/page.tsx
  src/styles/icons.ts
  src/styles/reset.ts
  tsconfig.json
  yarn.lock
Labels: 🧸 Feature, ⚒️ Fix, ⚒️ Refactor

#49 [Fix/#46] 요일별 API 연동 추가
  package.json
  public/apply-writer.svg
  src/components/NTag/index.tsx
  src/components/index.ts
  src/pages/home/Home.tsx
  src/pages/home/HomeDay.ts
  src/pages/home/HomeStyle.ts
  src/pages/home/_components/Apply/index.tsx
  src/pages/home/_components/Aricle/index.tsx
  src/pages/home/_components/DayArticle/index.tsx
  src/pages/home/_components/DayArticle/types.ts
  src/pages/home/_components/MainWriter/index.tsx
  yarn.lock
Labels: ⚒️ Fix, ⚒️ Refactor
